# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_question_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 15, 41, 50, 959100, tzinfo=utc)),
        ),
    ]
